spring.application.name=crafto-backend
server.port=8085
spring.data.mongodb.uri=${MONGODB_CONNECTION}
spring.data.mongodb.database=crafto_db

# Firebase Configuration
firebase.bucket-name=${BUCKET_NAME}
firebase.config.path=firebase-service-account.json

# Firebase Storage Configuration
firebase.storage.bucket=${BUCKET_NAME}
firebase.storage.download-url=https://storage.googleapis.com/%s/%s

# File upload size limits
# spring.servlet.multipart.max-file-size=5MB
# spring.servlet.multipart.max-request-size=16MB