spring.application.name=crafto-backend
server.port=8085
spring.data.mongodb.uri=mongodb+srv://nadamansoursamir_db_user:wtpmF0xPfUSLkkRE@craftocluster.ns5zjrh.mongodb.net/
spring.data.mongodb.database=crafto_db
